### ISSUE TITLE
Plot Job Running Cost

### ISSUE THREAD

**Issue by jonasbarth** [jonasbarth/nbd-2023-hw-1#7]
# Instructions
Plot the Job running cost $S$ as a function of $N$ for $N$ ranging between $1$ and $10000$. Let $S_{baseline}$ be the Job running cost in case **only server A** is used, i.e., the job is run locally on A. In the plot **normalize** $S$ with respect to $S_{baseline}$.

**Comment by JackVittori** [comment]
Added the code
